name: cao
on:
  workflow_dispatch:
   inputs:
      num:
        description: 'Offset of accounts to claim'
        default: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: runid
        run: |
          curl -X POST https://laobo.xyz/api/github/runid \
          -H "Content-Type: application/json" \
          -d "{\"run_id\": \"$GITHUB_RUN_ID\", \"name\": \"$GITHUB_WORKFLOW\", \"id\": \"${{ github.event.inputs.num }}\" }"

      - uses: actions/checkout@v4
        with:
          repository: tanomin/cao_baotangtruyen
          ref: master
          token: ${{ secrets.REMOTE_REPO_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Thay thế '3.x' bằng phiên bản Python bạn cần



      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Claim
        run: python main.py ${{ github.event.inputs.num }}
