name: upload mtt
on:
  workflow_dispatch:
   inputs:
      num:
        description: 'Offset of accounts to claim'
        default: '0'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tanomin/xtool
          ref: master
          token: ${{ secrets.REMOTE_REPO_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Thay thế '3.x' bằng phiên bản Python bạn cần

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Claim
        run: python main.py ${{ github.event.inputs.num }}